spring:
  security:
    enabled: false
  application:
    name: gateway-service
server:
  port: 8080
 
eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5
 
zuul:
  routes:
    project-manager:
      path: /project-manager/**
      sensitive-headers: Set-Cookie,Authorization
    iteration-manager:
      path: /iteration-manager/**
      sensitive-headers: Set-Cookie,Authorization
    discovery-server:
      path: /discovery/**
      sensitive-headers: Set-Cookie,Authorization
      url: http://localhost:8761
      
hystrix:
  command:
    project-manager:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds=600000
    iteration-manager:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds=600000
    discovery-server:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds=600000

management:
  security:
    enabled: false
