###
#   Database Settings
###
server:
  port: 8082
spring:
  application:
    name: project-manager
  cloud:
    config:
      label: latest
  dataSourceClassName: org.postgresql.ds.PGSimpleDataSource    
  datasource:
    jdbcUrl: jdbc:postgresql://10.10.58.62:3389/postgres?reWriteBatchedInserts=true
    platform: postgres
    username: postgres
    password:
    driverClassName: org.postgresql.Driver
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 50
        temp:
          use_jdbc_metadata_defaults: false
  open-in-view: false
  profiles:
    active: dev
  quartz:
    jdbc:
      initialize-schema: never
    job-store-type: jdbc
    properties:
      org:
        quartz:
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            isClustered: true
            misfireThreshold: 60000
            tablePrefix: qrtz_
            useProperties: true
          plugin:
            shutdownHook:
              class: org.quartz.plugins.management.ShutdownHookPlugin
              cleanShutdown: true
          scheduler:
            instanceId: AUTO
            instanceIdGenerator:
              class: com.gazis.projectmanager.quartz.CustomQuartzInstanceIdGenerator
            instanceName: project-manager
          threadPool:
            threadCount: 20    
    
eureka:
  client:
    region: default
    fetchRegistry: true
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
     
     
using:
  spring:
    schedulerFactory: true
quartz:
  enabled: true     
