###
#   Database Settings
###
server:
  port: 8082
spring:
  application:
    name: project-manager
  quartz: 
    job-store-type: jdbc
  cloud:
    config:
      label: latest
  datasource:
    url: jdbc:postgresql://10.10.58.62:3389/postgres?reWriteBatchedInserts=true
    platform: postgres
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 50
        temp:
          use_jdbc_metadata_defaults: false

eureka:
  client:
    region: default
    fetchRegistry: true
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
org:
  quartz:
    jobStore:
      class: org.quartz.impl.jdbcjobstore.JobStoreTX
      driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
      dataSource: quartzDataSource      
